baseurl = "/"
copyright = "pnyv dot sh"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
metaDataFormat = "yaml"
paginate = 10
title = "pnyv dot sh"
[[menu.docs]]
name = "Settings & Configuration"
weight = 7
[[menu.docs]]
name = "Editing"
weight = 4
[[menu.docs]]
name = "Quick Start"
weight = 2
[[menu.docs]]
name = "Media"
weight = 6
[[menu.docs]]
name = "Other"
weight = 8
[[menu.docs]]
name = "Hosting"
weight = 5
[[menu.docs]]
name = "Welcome"
weight = 1
[[menu.docs]]
name = "Git Sync"
weight = 3
[[menu.faqs]]
name = "Glossary"
weight = 2
[[menu.footer]]
name = "Product"
weight = 1
[[menu.footer]]
name = "Company"
weight = 2
[[menu.main]]
identifier = "signup"
name = "Sign up"
url = "https://app.forestry.io/signup"
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.OpenSearch]
baseName = "opensearch"
isPlainText = true
mediaType = "application/xml"
notAlternative = true
[outputFormats.Redirects]
baseName = "redirects"
isPlainText = true
mediatype = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "OpenSearch", "Algolia", "Redirects"]
[params]
dateformat = "January 2, 2006"
description = "A content management system for static sites built with Hugo and Jekyll. Get the speed, security, and reliability of static and the power of a Headless CMS."
ghrepo = "https://github.com/forestryio/forestry.io"
ghrepo_edit = "https://github.com/forestryio/forestry.io/edit/master/hugo/content/"
ghrepo_new = "https://github.com/forestryio/forestry.io/issues/new"
gtmid = "GTM-KL5HP9Q"
images = ["/uploads/2018/01/OGimage-01-3x.jpg"]
mixpanelid = "8aaf5d792dd5bf875adae0b2adac8900"

[social]
email = "support@forestry.io"
slack = "https://t.co/OANAJYol8Y"
twitter = "forestryio"
